project:
  type: website
  title: "MAST90084 - Statistical Modelling Scripts"
  output-dir: _output
  execute-dir: project

website:
  title: "MAST90084 - Statistical Modelling Scripts"
  navbar:
    left:
      - text: "Home"
        file: default.qmd
      - text: "Scripts"
        menu:
          - text: "ANOVA/Deviance Analysis"
            file: scripts/01-ANODEV.qmd
          - text: "Cell Differentiation"
            file: scripts/02-CellDiff.qmd
          - text: "Example 3.1 & 3.11 Caesar"
            file: scripts/03-Example3-1and3-11Caes.qmd
          - text: "Example 3.2 BTR"
            file: scripts/04-Example3-2BTR.qmd
          - text: "Tonsil Data"
            file: scripts/05-tonsil.qmd
          - text: "Happiness Data"
            file: scripts/06-Happiness.qmd
          - text: "Ohio Data"
            file: scripts/07-ohio.qmd
          - text: "GEE CTSIB"
            file: scripts/08-gee_ctsib.qmd
          - text: "GLM Mixed Effects"
            file: scripts/09-GLM_mixed_Effect.qmd
          - text: "LM Mixed Effects"
            file: scripts/10-LM_mixed_effect.qmd
          - text: "Survival Analysis"
            file: scripts/11-survival.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: false
    code-copy: true
    highlight-style: a11y
    page-layout: article
