project:
  type: website
  title: "MAST90084 - Statistical Modelling Scripts"
  output-dir: _output
  execute-dir: project

website:
  title: "MAST90084 - Statistical Modelling Scripts"
  repo-url: https://github.com/jaycrick/MAST90084-Statistical-Modelling-Scripts
  repo-actions: [edit, issue]
  # bread-crumbs: true
  page-navigation: true
  navbar:
    left:
      - text: "Home"
        file: default.qmd
      - text: "Scripts"
        menu:
          - text: "Binomial GLMS: Caesarian Birth"
            file: quarto_scripts/01-ANODEV.qmd
          - text: "(Quasi-)Poisson GLM: Cell Differentiation"
            file: quarto_scripts/02-CellDiff.qmd
          - text: "Multinomial Logistic Regression: Caesarian Birth"
            file: quarto_scripts/03-Example3-1and3-11Caes.qmd
          - text: "Ordinal Regression: Breathing Test Results"
            file: quarto_scripts/04-Example3-2BTR.qmd
          - text: "Sequential Regression: Tonsil Size"
            file: quarto_scripts/05-tonsil.qmd
          # - text: "Happiness Data"
          #   file: quarto_scripts/06-Happiness.qmd
          # - text: "Ohio Data"
          #   file: quarto_scripts/07-ohio.qmd
          # - text: "GEE CTSIB"
          #   file: quarto_scripts/08-gee_ctsib.qmd
          # - text: "GLM Mixed Effects"
          #   file: quarto_scripts/09-GLM_mixed_Effect.qmd
          # - text: "LM Mixed Effects"
          #   file: quarto_scripts/10-LM_mixed_effect.qmd
          # - text: "Survival Analysis"
          #   file: quarto_scripts/11-survival.qmd
          - text: "APPENDICES"
          - text: "Appendix 1: Dispersion with Working Residuals"
            file: quarto_scripts/A1-dispersion-working-residuals.qmd
          - text: "Appendix 2: Likelihood for Grouped and Ungrouped Multinomial Data"
            file: quarto_scripts/A2-likelihood-multinomial.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: show
    code-copy: true
    highlight-style: a11y
    page-layout: article

bibliography: references.bib